### ISSUE TITLE
Fibaro door sensor & switches support

### ISSUE THREAD

**Issue by capi92** [Hellorheaven/xpl-zibase#7]
Hi,

For whatever reason, the ON message is different with Fibaro door sensor.

Thus, in order to work, the following is required in ZiBase.pm : 
    693       if ($devid =~ /^(Z[A-P]\d\d?)_ON$/) {
    694       $self->xpl_send_rfcmd($1, 'on', 'zwave', 100);
    695     }
    696     if ($devid =~ /^(Z[A-P]\d\d?)$/) {
    697       $self->xpl_send_rfcmd($1, 'on', 'zwave', 100);
    698     }

This allow to have on and off event instead of battery level only on XPL.

Regards,

Pierre

**Comment by Hellorheaven** [comment]
Hi Pierre, 

Could you please give me the output message of the zibase for each status of your fibaro module?

Thanks

Mickael 

PS: i'm french ;)

**Comment by capi92** [comment]
Bonjour,

Des traces en mode debug ou un tcpdump ?

Cdt,

Pierre

2014/1/10 ZERBIB Mickael notifications@github.com

**Comment by Hellorheaven** [comment]
bonjour,

oui j'aurais besoin des messages envoyée pour chaque statut de tes modules zwave. 2 méthodes:

soit tu vas dans le suivie d'activité en mode expert 
soit tu lance en ligne de commande le xpl-zibase en mode debug: xpl-zibase -interface eth0 --verbose --zibase-verbose

et tu changes l'état de tes capteurs.

les miens de modules ont trois états on, off, dim/special(pour les modules dimmable et volet roulant)

cdt,

Mickael

**Comment by capi92** [comment]
Bonjour,

Ci-joint le dump pour un dimmer fibaro et un capteur d'ouverture de porte fibaro.

Pierre

---

Listening on 127.0.0.1:36391
Sending on 127.0.0.1
Listening ZiBase messages on 0.0.0.0:28734
Found ZiBase 'ZiBASExxxxxx' at IP 192.168.0.x
Received : Zapi linked to host IP=<zip>127.0.0.1</zip> UDP Port=<zudp>28734</zudp>
Received : Received radio ID (<rf>ZWAVE ZA4</rf>  <dev>CMD/INTER</dev>  Batt=<bat>Ok</bat>): <id>ZA4</id>
xpl-trig/sensor.basic: domoserv-zibase.centos -> \* ZA4/battery/Ok
Received : Received radio ID (<rf>ZWAVE ZA4</rf>  <dev>CMD/INTER</dev>  Batt=<bat>Ok</bat>): <id>ZA4_OFF</id>
xpl-trig/sensor.basic: domoserv-zibase.centos -> \* ZA4_OFF/battery/Ok
xpl-trig/rfcmd.basic: domoserv-zibase.centos -> \* za4/off/zwave
Received : Received radio ID (<rf>ZWAVE ZA4</rf>  <dev>CMD/INTER</dev>  Batt=<bat>Ok</bat>): <id>ZA4</id>
xpl-trig/sensor.basic: domoserv-zibase.centos -> \* ZA4/battery/Ok
Received : Received radio ID (<rf>ZWAVE ZA4</rf>  <dev>CMD/INTER</dev>  Batt=<bat>Ok</bat>): <id>ZA4_OFF</id>
xpl-trig/sensor.basic: domoserv-zibase.centos -> \* ZA4_OFF/battery/Ok
xpl-trig/rfcmd.basic: domoserv-zibase.centos -> \* za4/off/zwave
Received : Received radio ID (<rf>ZWAVE ZB6</rf> <dev>WakeUp</dev> Batt=<bat>Ok</bat>): <id>WZB6</id>
xpl-trig/sensor.basic: domoserv-zibase.centos -> \* WZB6/battery/Ok
Received : Received radio ID (<rf>ZWAVE ZA15</rf> <dev>Low-Power Measure</dev> Total Energy=<kwh>0.2</kwh>kWh Power=<w>00</w>W Batt=<bat>Ok</bat>): <id>PZA15</id>
xpl-trig/sensor.basic: domoserv-zibase.centos -> \* PZA15/energy/0.2
xpl-trig/sensor.basic: domoserv-zibase.centos -> \* PZA15/battery/Ok
Received : Received radio ID (<rf>ZWAVE ZB6</rf> <dev>WakeUp</dev> Batt=<bat>Ok</bat>): <id>WZB6</id>
xpl-trig/sensor.basic: domoserv-zibase.centos -> \* WZB6/battery/Ok
Received : Received radio ID (<rf>ZWAVE ZA14</rf>  <dev>CMD/INTER</dev>  Batt=<bat>Ok</bat>): <id>ZA14</id>
xpl-trig/sensor.basic: domoserv-zibase.centos -> \* ZA14/battery/Ok
Received : Received radio ID (<rf>ZWAVE ZA14</rf>  <dev>CMD/INTER</dev>  Batt=<bat>Ok</bat>): <id>ZA14_OFF</id>
xpl-trig/sensor.basic: domoserv-zibase.centos -> \* ZA14_OFF/battery/Ok
xpl-trig/rfcmd.basic: domoserv-zibase.centos -> \* za14/off/zwave
Received : Received radio ID (<rf>ZWAVE ZA14</rf>  <dev>CMD/INTER</dev>  Batt=<bat>Ok</bat>): <id>ZA14</id>
xpl-trig/sensor.basic: domoserv-zibase.centos -> \* ZA14/battery/Ok
Received : Received radio ID (<rf>ZWAVE ZA14</rf>  <dev>CMD/INTER</dev>  Batt=<bat>Ok</bat>): <id>ZA14_OFF</id>
xpl-trig/sensor.basic: domoserv-zibase.centos -> \* ZA14_OFF/battery/Ok
xpl-trig/rfcmd.basic: domoserv-zibase.centos -> \* za14/off/zwave

**Comment by Hellorheaven** [comment]
Bonjour,

c'est corrigé normalement.

pourrais tu tester?

Merci.

Mickael
